Repository magento/graphql-ce, pull requests merged in 2018-07, with the labels that each got.

#94 Changed canonical_url to relative_url
  app/code/Magento/UrlRewriteGraphQl/Model/Resolver/UrlRewrite.php
  app/code/Magento/UrlRewriteGraphQl/etc/schema.graphqls
Labels: requires-documentation

#103 hidden product attributes not intended for storefront
  app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Attributes/Collection.php
Labels: 2.3-develop, Imported, Partner: Atwix, partners-contribution, requires-documentation, requires-tests

#99 #96 Make category query compatible with staging
  app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/CategoryTest.php
Labels: 2.3-develop, Imported, Partner: Atwix, commerce, partners-contribution
