Repository magento/graphql-ce, pull requests merged in 2019-01, with the labels that each got.

#301 Mutation placeholder removed
  app/code/Magento/GraphQl/etc/schema.graphqls
Labels: Partner: Atwix, Release Line: 2.3, partners-contribution

#302 Fix spelling in schema comments
  app/code/Magento/StoreGraphQl/etc/schema.graphqls
Labels: Release Line: 2.3

#312 Fix region_id update in updateCustomerAddress mutation
  app/code/Magento/CustomerGraphQl/Model/Resolver/UpdateCustomerAddress.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/UpdateCustomerAddressTest.php
Labels: Partner: Something Digital, Release Line: 2.3, bug, partners-contribution

#318 [ThemeGraphql] Getting values from StoreConfig is not possible
  app/code/Magento/ThemeGraphQl/etc/graphql/di.xml
Labels: Partner: Atwix, Release Line: 2.3, partners-contribution
