Repository magento/graphql-ce, pull requests merged in 2019-04, with the labels that each got.

#473 Tests data rollback for`\Magento\GraphQl\Customer\CreateCustomerTest::testCreateCustomerAccountWithPassword
  dev/tests/api-functional/testsuite/Magento/GraphQl/Customer/CreateCustomerTest.php
Labels: Partner: ISM eCompany, Progress: accept, Release Line: 2.3, partners-contribution

#545 magento/graphql-ce#544: Replace deprecated fixtures in RemoveItemFromCartTest
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/RemoveItemFromCartTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/GetQuoteItemIdByReservedQuoteIdAndSku.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/RemoveItemFromCartTest.php
Labels: Partner: Atwix, Progress: accept, Release Line: 2.3, partners-contribution, test-coverage

#582 graphQl-579: added test coverage for setting disabled shipping method
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SetShippingMethodsOnCartTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/SetShippingMethodsOnCartTest.php
Labels: Partner: Atwix, Progress: accept, Release Line: 2.3, partners-contribution

#584 graphQl-580: set disabled payment method test coverage
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SetPaymentMethodOnCartTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/SetPaymentMethodOnCartTest.php
Labels: Partner: Atwix, Progress: accept, Release Line: 2.3, partners-contribution

#586 graphQl-581: set shipping method on an empty cart test coverage
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SetShippingMethodsOnCartTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/SetShippingMethodsOnCartTest.php
Labels: Partner: Atwix, Progress: accept, Release Line: 2.3, partners-contribution

#616 Added test coverage for Adding simple product to cart functionality
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/AddSimpleProductToCartTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/AddSimpleProductToCartTest.php
Labels: Partner: Atwix, Progress: accept, Release Line: 2.3, partners-contribution

#639 GraphQl-575: Schema inconsistency of "SelectedShippingMethod" declaration
  app/code/Magento/CatalogGraphQl/etc/schema.graphqls
  app/code/Magento/GraphQl/etc/schema.graphqls
  app/code/Magento/QuoteGraphQl/Model/Resolver/ShippingAddress/SelectedShippingMethod.php
  app/code/Magento/QuoteGraphQl/etc/schema.graphqls
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/GetSelectedShippingMethodTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SetOfflineShippingMethodsOnCartTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SetShippingMethodsOnCartTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/GetSelectedShippingMethodTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/SetOfflineShippingMethodsOnCartTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/SetShippingMethodsOnCartTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Ups/SetUpsShippingMethodsOnCartTest.php
Labels: Component: CatalogGraphQl, Component: GraphQl, Component: QuoteGraphQl, Release Line: 2.3
