Repository magento/graphql-ce, pull requests merged in 2019-02, with the labels that each got.

#328 Changed hard coded "configurable" to Configurable::TYPE_CODE
  app/code/Magento/ConfigurableProductGraphQl/Model/ConfigurableProductTypeResolver.php
Labels: Partner: ISM eCompany, Release Line: 2.3, partners-contribution

#329 Add missing argument PHPDoc comment
  app/code/Magento/BundleGraphQl/Model/Resolver/Options/Collection.php
Labels: Partner: ISM eCompany, Release Line: 2.3, partners-contribution

#337 graphQl-336: Magento/CatalogGraphQl/Model/Category/LevelCalculator class has fields declared dynamically
  app/code/Magento/CatalogGraphQl/Model/Category/LevelCalculator.php
Labels: Release Line: 2.3

#341 graphQl-255: Test coverage for PR-243
  dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/CategoryProductsCountTest.php
Labels: Release Line: 2.3

#383 Query Cart returns internal server error if configurable product was added
  app/code/Magento/QuoteGraphQl/etc/di.xml
Labels: Partner: ISM eCompany, Progress: accept, Release Line: 2.3, partners-contribution

#385 GraphQL-292: Cleanup quote GraphQL scheme
  app/code/Magento/ConfigurableProductGraphQl/etc/schema.graphqls
  app/code/Magento/QuoteGraphQl/etc/schema.graphqls
Labels: Progress: accept, Release Line: 2.3

#390 Save country when creating new quote addresses
  app/code/Magento/QuoteGraphQl/Model/Cart/SetBillingAddressOnCart.php
  app/code/Magento/QuoteGraphQl/Model/Cart/SetShippingAddressOnCart.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/SetBillingAddressOnCartTest.php
  dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/SetShippingAddressOnCartTest.php
Labels: Component: QuoteGraphQl, Partner: Something Digital, Progress: accept, Release Line: 2.3, partners-contribution
